import './globals.css';
import type { Metadata } from 'next';
import { Inter, Happy_Monkey } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const happyMonkey = Happy_Monkey({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={happyMonkey.className}>{children}</body>
    </html>
  );
}
